### PR TITLE
Use IO Visor's domain name

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by drzaeus77** [comment]
Hmm, thanks for updating, and also thanks even for testing it :)

Couple things:
1. could switch to https
2. trusty is no longer being updated, later we should try out a xenial baseline
3. if we use xenial instead of xenial-nightly, we can drop the trusted=yes bit since the tagged packages are signed

For now, can you just try number 1?

**Comment by pchaigno** [comment]
> For now, can you just try number 1?

Done.

> trusty is no longer being updated, later we should try out a xenial baseline

Shouldn't we try yakkety directly?

**Comment by zoidbergwill** [comment]
Looks like this has been contributed by someone else since then: https://github.com/iovisor/xdp-vagrant/commit/d52f4c801f2150c17ee907a4ac4c3f435f61cac4

**Comment by zoidbergwill** [comment]
For suggestion 2, should we make an issue to track upgrading to xenial, so we can try upgrading to bionic when it comes out later this month?

**Pull request closed without merging**
